### PR TITLE
extend .gitignore, images css

### PR DESCRIPTION
**Pull request by cgeorgilakis**
PR for having custom icons. 
Icons should be small like that of ORCID( 16x16). We use % for css class because if you write it with px Keycloak says Invalid property value!

In vanilla theme we will have only common classes in order to support proper IdP icons. Icons, icons configuration and css class must be configured in inherited themes.
Proper configuration:

- add icon to img folder
- add class in style.css
 ```
.orcid-logo {
    background-image: url(../img/orcid-logo.png);
}
```
- add _'kcLogoIdP-orcid= fa fa-extend orcid-logo'_ in theme.properties. Where orcid is IdP alias and orcid-logo css class name with proper icon.

Working example: https://login-devel.einfra.grnet.gr/auth/realms/einfra/account/ . IdPs : orcid, grnet, egi foundation.

### CODE REVIEW

**Comment by laskasn** [comment]
Need to also check how the caching works in ftl templates (damn). As i take a little peek into this thing, i see that there are 2 layers of caching. One on keycloak side implemented with in-memory maps. Underlying, a second one, using TemplateCache and CacheStorage of freemarker library. (IT'S A HUGE MESS)
More details, soon.

**Comment by cgeorgilakis** [comment]
> Need to also check how the caching works in ftl templates (damn). As i take a little peek into this thing, i see that there are 2 layers of caching. One on keycloak side implemented with in-memory maps. Underlying, a second one, using TemplateCache and CacheStorage of freemarker library. (IT'S A HUGE MESS) More details, soon.

Cache is a nightmare! Maybe we need to do crucial  changes.
However, this issue is not relevant with this PR for icons.

**Comment by laskasn** [comment]
> > Need to also check how the caching works in ftl templates (damn). As i take a little peek into this thing, i see that there are 2 layers of caching. One on keycloak side implemented with in-memory maps. Underlying, a second one, using TemplateCache and CacheStorage of freemarker library. (IT'S A HUGE MESS) More details, soon.
> 
> Cache is a nightmare! Maybe we need to do crucial changes. However, this issue is not relevant with this PR for icons.

ok, we should have a dedicated discussion for that.

> PR for having custom icons. Icons should be small like that of ORCID( 16x16). We use % for css class because if you write it with px Keycloak says Invalid property value!
> 
> In vanilla theme we will have only common classes in order to support proper IdP icons. Icons, icons configuration and css class must be configured in inherited themes. Proper configuration:
> 
> * add icon to img folder
> * add class in style.css
> 
> ```
> .orcid-logo {
>    background-image: url(../img/orcid-logo.png);
> }
> ```
> 
> * add _'kcLogoIdP-orcid= fa fa-extend orcid-logo'_ in theme.properties. Where orcid is IdP alias and orcid-logo css class name with proper icon.
> 
> Working example: https://login-devel.einfra.grnet.gr/auth/realms/einfra/account/ . IdPs : orcid, grnet, egi foundation.

I propose keeping all the icons in the vanilla theme. The vanilla should have all the icons for the IdPs (which won't change between project deployments), while, the things which should change between projects are the "project logo" , the "project terms of use", the "project licence", etc

**Comment by cgeorgilakis** [comment]
@laskasn I aggree with your idea about keeping all icons configuration the vanilla theme. With this we could keep IdPs ui configuration common. If an IdP is not exist in a Keycloak version, we will not have any problem. Of cource, we have the possibility to put specific IdPs in extended themes.

@NicolasLiampotis do you agree?

**Review by laskasn — APPROVED** [review]
i think it looks good (thanks for the deployment). My only comment is that i believe that we need to have all the common icons (i.e. GRNet etc) in the vanilla theme codebase

**Comment by cgeorgilakis** [comment]
> i think it looks good (thanks for the deployment). My only comment is that i believe that we need to have all the common icons (i.e. GRNet etc) in the vanilla theme codebase

I agree. We should decide it in our meeting and after I could enhance this PR.

**Pull request merged**
